name: pet_shouq
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.5
  intl: any
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   modal_bottom_sheet: ^3.0.0-pre
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#FFD0A6"
  adaptive_icon_foreground: "assets/images/android_12_logo.png"

flutter_native_splash:
  background_image: "assets/images/splash_bg.png"
  image: assets/images/android_12_logo.png
  android_12:
    image: assets/images/android_12_logo.png
    color: "#FFD0A6"

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/samples/
    - assets/locale/en.json
