export 'onboarding/onboarding.dart';
export 'login/login.dart';
export 'register/register.dart';
export 'verification/verification.dart';
export 'forgotPassword/forgot_password.dart';
export "changePassword/change_password.dart";
export "dashboard/dashboard.dart";
export "parent/parent.dart";
export "doctorDetails/doctor_details.dart";
