const List<String> breedList = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Alaskan Malamute",
  "American Bully",
  "American Eskimo Dog",
  "American Pit Bull Terrier",
  "Anatolian Shepherd Dog",
  "Australian Shepherd",
  "Basenji",
  "Basset Hound",
  "Bedlington Terrier",
  "Belgian Shepherd",
  "Bichon Frisé",
  "Black Russian Terrier",
  "Border Collie",
  "Borzoi",
  "Boston Terrier",
  "Brittany",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Dachshund",
  "Dalmatian",
  "Dobermann",
  "English Cocker Spaniel",
  "French Bulldog",
  "German Shepherd",
  "Golden Retriever",
  "Goldendoodle",
  "Havanese",
  "Jack Russell Terrier",
  "Labradoodle",
  "Labrador Retriever",
  "Maltese dog",
  "Maltipoo",
  "Newfoundland dog",
  "Pembroke Welsh Corgi",
  "Pomeranian",
  "Poodle",
  "Rottweiler",
  "Samoyed",
  "Sarabi dog",
  "Sheltie",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Yorkshire Terrier"
];
